version: '0.1.0'

services:
  bot:
    build: ./bot
    entrypoint: ["/bin/bot", "--token", "${TOKEN}", "--spid", "${SPOTIFY_CLIENT_ID}", "--spsecret", "${SPOTIFY_SECRET}", "--env", "${ENVIRONMENT}"]
  web-app:
    build: ./web
    entrypoint: ["/bin/server", "--port", "${PORT}", "--env", "${ENVIRONMENT}"]
